### ISSUE TITLE
Possibly a typo in the code.

### ISSUE THREAD

**Issue by aleksey-r** [volks73/cargo-wix#106]
The parameter "culture" for the Russian language is ru_ru instead of ru-ru.
https://github.com/volks73/cargo-wix/blob/master/src/lib.rs
```rust
Cultures::RuRu => write!(f, "ru_RU"),
...
"ru_ru" => Ok(Cultures::RuRu),
...
```
Result of "cargo wix -c ru-ru" execution:
```
Error[2] (Generic): Unknown 'ru-ru' culture
```
Result of "cargo wix -c ru_ru" execution:
```
Error[1] (Command): The 'light' application failed with exit code = 102. Consider using the '--nocapture' flag to obtain more information.
```

**Comment by volks73** [comment]
Fixed as of 508e3e152eaa6d9ee851c75c7b3e6aaecdca6c9b.

Creating a new release shortly.
