### ISSUE TITLE
Rename `CargoTarget` WiX variable to `RustcTarget`

### ISSUE THREAD

**Issue by volks73** [volks73/cargo-wix#125]
Reading through the documentation for Cargo recently, a Cargo "target" is a binary, `[[bin]]`, or a library, `[lib]`, as defined in a package's manifest (Cargo.toml). This is not the target triple. The "triple" is the Rust compiler's (rustc) target, as seen with the `rustc --print target-list` command. However, there is the `cargo build --target <TARGET>` option, which is mimicked in this subcommand, and takes the "triple". Unfortunately, the word "target" appears to be overloaded within Cargo/Rustc. The `CargoTarget` for this subcommand is referring to the rustc target, not a target defined in the package's manifest. To avoid confusion on the origin and expected format of the variable's value, maybe it should be renamed to `RustcTarget`, `TargetTriple`, or `RustcTargetTriple`. The last one is my current preference because it is the most descriptive, but it is verbose.

**Comment by volks73** [comment]
@roblabla Do you have any thoughts or suggestions?

**Comment by roblabla** [comment]
Ah, yes, i got bit by this in the past. Target is used by every compiler to mean the architecture we're compiling for. Cargo overloading the term is unfortunate.

TargetTriple seems fine by me.

**Comment by volks73** [comment]
@roblabla I am good with `TargetTriple`, too. Would you like to make the change or should I?
