### ISSUE TITLE
packaging wrong bin in cross builds

### ISSUE THREAD

**Issue by cstkingkey** [volks73/cargo-wix#150]
running cargo wix --target=i686-pc-windows-msvc
the buiding stage trigger right binary out, and msi file do have a x86 name, but the bin in the msi is 64bit version.

**Comment by volks73** [comment]
I am not too familiar with the cross-compilation support. It was mostly spread-headed by @roblabla. Maybe @roblabla can provide some information on cross-compilation with the `--target` option?

**Comment by roblabla** [comment]
At work, we use cargo-wix with --no-build along with --target, so it's possible --target has a bug. Maybe I forgot to propagate the target down to cargo build?

I'll look into it tomorrow.

**Comment by cstkingkey** [comment]
use $(var.CargoTargetBinDir)  instead in wxs make it work.

**Comment by cstkingkey** [comment]
turn out the wxs is generated by 0.3.1. so latest version has no such issue.
