### ISSUE TITLE
cargo wix sign always sign first msi file

### ISSUE THREAD

**Issue by cstkingkey** [volks73/cargo-wix#153]
cargo wix sign always sign first msi file regardless of targets. 
it should find target msi file.

**Comment by cstkingkey** [comment]
It throw Error[3] (Io): The '.\target\wix\installer.msi' path does not exist.
And help msg for sign say  <INPUT>  is for Cargo.toml

**Comment by volks73** [comment]
Is the MSI you are trying to sign actually named `installer.msi`? I just used that in my command as an example. I should have clarified.

The help message might be incorrect, too.

**Comment by cstkingkey** [comment]
I replaced actual binary name with it.
