### ISSUE TITLE
About adding external DLLs in certain directory

### ISSUE THREAD

**Issue by powerory** [volks73/cargo-wix#161]
Hi,

According to comment(https://github.com/volks73/cargo-wix/issues/76#issuecomment-522729742), adding external DLL to package could be done by adding some lines to `main.wxs`.

But in case of that there are too many DLLs to be included, modifying `main.wxs` manually can be a burden.
Is there a way to include all files(or only .dll) in specific directory?

**Comment by volks73** [comment]
Thank you for your question. Please take a look at my comment in https://github.com/volks73/cargo-wix/issues/140#issuecomment-835830170. Specifically,

>If there are a relatively large number of files, then I would recommend investigating the [Heat](https://wixtoolset.org/documentation/manual/v3/overview/heat.html) utility provided with the WiX Toolset, which is specifically designed to harvest and/or bundle folders of files into an installer. The [StackOverflow](https://stackoverflow.com/) question, [Include all Files in Bin folder in Wix Installer](https://stackoverflow.com/questions/36756311/include-all-files-in-bin-folder-in-wix-installer), provides some excellent answers for using Heat and including whole folders in a WXS file.

It sounds like the Heat utility provided by the WiX Toolset would help with automating the inclusion of a large number of DLLs, or other external resources/assets.

**Comment by powerory** [comment]
Oh, I am sorry for that I did not find that question and answer.
Thank you for your guide! :)

**Comment by volks73** [comment]
No worries. It is all good. It looks like this question has been answered, so I am going to close this issue. Thank you!
