### ISSUE TITLE
How to set multilingual support?

### ISSUE THREAD

**Issue by songlinshu** [volks73/cargo-wix#169]
Hi,How to set multilingual support?,(Example: FR,CN....)

**Comment by volks73** [comment]
Thank you for your interest in the cargo-wix subcommand.

multilingual support is provided through the [WiX UI localization support](https://wixtoolset.org/documentation/manual/v3/wixui/wixui_localization.html) via the [`-c,--culture`](https://volks73.github.io/cargo-wix/cargo_wix/index.html#-c--culture) and [`-l,--locale`](https://volks73.github.io/cargo-wix/cargo_wix/index.html#-l--locale) command line options.

The locale and culture can also be defined and set in the [`[package.metadata.wix]`](https://volks73.github.io/cargo-wix/cargo_wix/index.html#configuration) section of a project's manifest.

**Comment by volks73** [comment]
I believe this question has been answered, so I am closing the issue.
