### ISSUE TITLE
Error[1] (Command): The 'candle' application failed with exit code = 199

### ISSUE THREAD

**Issue by 3togo** [volks73/cargo-wix#171]
when I run "cargo wix", it failed with the following error message:

Error[1] (Command): The 'candle' application failed with exit code = 199

How to fix it?

**Comment by volks73** [comment]
Do you have the [WiX toolset](https://wixtoolset.org/) installed? If yes, which version?

Did you are already run the `cargo wix init` command?

Would you be able to elaborate more on your environment, project structure, and the series of events that lead to the error?

Can you run the `cargo wix -vvv --no-capture` command and provide the log and output?

**Comment by volks73** [comment]
I am closing as there has been no response or follow-up for some time.
