### ISSUE TITLE
MSRV needs to be bumped, move to 2021 edition?

### ISSUE THREAD

**Issue by sharifhsn** [volks73/cargo-wix#186]
The README says that the minimum supported Rust version (MSRV) is 1.40.0, but this is no longer true since the update to `clap v4`. `clap` requires 1.64.0 as its MSRV, which means that the MSRV for `cargo-wix` is also `1.64.0`.

Since we're updating the MSRV anyway, the project could also be moved to the 2021 edition. I checked, and there would not need to be any changes if moving to the 2021 edition, but `clippy` would warn on the manual implementations for `Default` for enums, since that can now happen automatically. I can make these changes if they are desired.

**Comment by volks73** [comment]
The MSRV should be bumped. I would appreciate a PR that replaces the manual `Default` implementations for enums to automatic implementations.

However, the tests need to be refactored if the MSRV is going to be bumped. See https://github.com/volks73/cargo-wix/issues/146. Would you be able to address that issue, too?

**Comment by slonopotamus** [comment]
Whoops. You possibly also want to set up CI testing against oldest supported Rust version on CI, so next time such accidental bump doesn't go unnoticed and becomes a conscious decision.
