### ISSUE TITLE
Can this crate be used to make a screen saver?

### ISSUE THREAD

**Issue by yohlimem** [volks73/cargo-wix#194]
I've wanted to create a screensaver for myself, so I'd like to know if this is possible with this crate.

**Comment by volks73** [comment]
No, this crate cannot be used to make a screen saver. This crate can be used to create a Windows installer (msi) through usage of the [WiX Toolset](https://wixtoolset.org/). I am not aware of the WiX Toolset being able to create screen savers, but if WiX Toolset has this capability it is currently not support in this crate.

**Comment by yohlimem** [comment]
Yeah, chat GPT confused me. he told me I can use an MSI file to install a screensaver but apparently, you just need to rename an EXE file to SCR and install it... weird that I couldn't find that on google since it's really simple.

**Comment by volks73** [comment]
I am going to close as it appears the question has been answered.
