### ISSUE TITLE
thanks for all the help!

### ISSUE THREAD

**Issue by Gankra** [volks73/cargo-wix#242]
Just wanted to let you know that cargo-wix is now part of cargo-dist, shipped in 0.3.0!

* [docs](https://opensource.axo.dev/cargo-dist/book/installers/msi.html)
* [example application using the feature](https://opensource.axo.dev/axolotlsay/)

So you might be getting a lot more traffic from our users, feel free to ping me for help! 😺

**Comment by volks73** [comment]
Cool. Your welcome, and thank you for the excellent PRs. The documentation looks great.
