### ISSUE TITLE
Add support for the Wix Toolset installed WIX system environment variable

### ISSUE THREAD

**Issue by volks73** [volks73/cargo-wix#53]
Based comments from @fschutt in #46, I did not realize that the WiX Toolset created the `WIX` system environment variable during installation when I first added support for the `WIX_PATH` environment variable to this sub-command. I had always wondered why the WiX Toolset installer did not add the `bin` folder to the `PATH` system environment variable automatically.

So, it might make more sense to change support of the `WIX_PATH` environment variable to the `WIX` system environment variable and possibly avoiding needing to avoid the `PATH` system environment variable and including warnings/instructions about adding the `bin` folder to the PATH.

I would like to double check that the WiX Toolset as of v3.11 creates the `WIX` system environment variable during installation.

**Comment by fschutt** [comment]
It does, however the `WIX` environment variable doesn't point to the `\bin` folder, just the top folder where WiX is installed:

![image](https://user-images.githubusercontent.com/12084016/40258326-7cd55c52-5af1-11e8-8535-992ddcbcb717.png)

I don't actually have a `WIX_PATH` variable...

**Comment by volks73** [comment]
The WIX system environment variable is used as of dc611c8a582a9fab94fc0e8a41a37a2162dbd6d8, and it replaces the WIX_PATH environment variable functionality.
